apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 1
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - image: miriamsafwat/udagram-api-feed:latest
        name: udagram-api-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"  
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - name: aws-config-volume
          mountPath: /root/.aws
      restartPolicy: Always
      volumes:
        - name: aws-config-volume
          secret:
            secretName: aws-secret