apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend
spec:
  selector:
    matchLabels:
      service: udagram-frontend
  replicas: 3
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
      - image: miriamsafwat/udagram-frontend:latest
        name: udagram-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - name: aws-config-volume
          mountPath: /root/.aws
      restartPolicy: Always
      volumes:
        - name: aws-config-volume
          secret:
            secretName: aws-secret