apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  selector:
    matchLabels:
      service: udagram-reverseproxy
  replicas: 3
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
      - image: miriamsafwat/udagram-reverseproxy:latest
        name: udagram-reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-configmap
        volumeMounts:
        - name: aws-config-volume
          mountPath: /root/.aws
      restartPolicy: Always
      volumes:
        - name: aws-config-volume
          secret:
            secretName: aws-secret